function DashboardPage() {
  return (
    <div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
    </div>
  )
}

export default DashboardPage
